import Head from "next/head";
import Image from "next/image";
import elfantLogo from "/public/img/elfantlogo.gif";
import styles from '../styles/Layout.module.css'

const Layout = ( {children} ) =>{
    return (
        <div className={styles.pageBox}>
          <Head>
            <title>Open House Check-in</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <main className={styles.page}>
          <section className={styles.container}>
            <div className={styles.formBox}>
                <div className={styles.logo}>
                    <Image className={styles.compLogo} src={elfantLogo} width={527} height={233}/>
                </div>
                <div className={styles.bottomBox}>
                    { children }
                </div>
            </div>
        </section>
        </main>
        </div>
      )
}

export default Layout;