import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/ThankYou.module.css'
import {name} from '../index';

export default function ThankYou() {
  return (
    <div className={styles.pageContainer}>
      <Head>
        <title>Open House Check-in</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.pageBox}>
      <section className={styles.container}>
        <div className={styles.formBox}>
            <div className={styles.logo}>
                <Image className={styles.compLogo} src="/../public/img/elfantlogo.gif" width={527} height={233}/>
            </div>
        <div className={styles.thankYouBox}>
              <h1 className={styles.ThankYou}>{`Thank you, ${name}!`}</h1>
          </div>
        </div>
    </section>
    </main>
    </div>
 )
}